"""init

Revision ID: 64a6ca17e434
Revises:
Create Date: 2022-10-25 01:01:35.153137

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "64a6ca17e434"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tag_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reddit_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("icon_img", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_employee", sa.Boolean(), nullable=False),
        sa.Column("opted_out", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ref_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_player_id"), "player", ["id"], unique=False)
    op.create_index(op.f("ix_player_ref_id"), "player", ["ref_id"], unique=False)
    op.create_table(
        "subreddit",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sub_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ref_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subreddit_id"), "subreddit", ["id"], unique=False)
    op.create_index(op.f("ix_subreddit_ref_id"), "subreddit", ["ref_id"], unique=False)
    op.create_table(
        "game",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("subreddit_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ref_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subreddit_id"],
            ["subreddit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_game_id"), "game", ["id"], unique=False)
    op.create_index(op.f("ix_game_ref_id"), "game", ["ref_id"], unique=False)
    op.create_table(
        "gameplayerlink",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("game_id", "player_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gameplayerlink")
    op.drop_index(op.f("ix_game_ref_id"), table_name="game")
    op.drop_index(op.f("ix_game_id"), table_name="game")
    op.drop_table("game")
    op.drop_index(op.f("ix_subreddit_ref_id"), table_name="subreddit")
    op.drop_index(op.f("ix_subreddit_id"), table_name="subreddit")
    op.drop_table("subreddit")
    op.drop_index(op.f("ix_player_ref_id"), table_name="player")
    op.drop_index(op.f("ix_player_id"), table_name="player")
    op.drop_table("player")
    # ### end Alembic commands ###
