version: '3'

services:
  db-test:
    image: postgres:14.1-alpine
    env_file:
      - .env
    ports:
      - '5431:5432'

  tag:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        env: "TEST"
    ports:
      - "8666:8000"
    command: |
        bash -c "
        while !</dev/tcp/db/5432; do sleep 1; done;
        pytest --cov-report=xml:/data/coverage.xml --cov=tag_youre_it/ tests/"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - /data:/data  # to access coverage.xml
