version: '3'

volumes:
  base-data:
  db-data:

services:
  db:
    image: postgres:14.1-alpine
    env_file:
      - .env
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  tag:
    restart: always
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        env: ${ENV}
    ports:
      - "8666:8000"
    command: |
        bash -c "
        while !</dev/tcp/db/5432; do sleep 1; done;
        python3 ./play.py"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - base-data:/data
      - ./:/code
